# Generated by Django 2.1.3 on 2018-11-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=10, null=True)),
                ('seat_count', models.IntegerField()),
                ('has_projector', models.BooleanField(default=False)),
                ('building', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('descr', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=20)),
                ('begin_date', models.DateTimeField(verbose_name='Begin date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('user_passw', models.CharField(max_length=25)),
                ('is_administrator', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimng.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimng.Classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimng.Course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimng.Period')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimng.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=60)),
                ('begin_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unimng.Time_Block'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('professor', 'course', 'period', 'time_block', 'classroom')},
        ),
    ]
