# Generated by Django 2.1.3 on 2018-12-01 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='unimng.Department'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='unimng.Classroom'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='unimng.Course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='unimng.Period'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='unimng.Professor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='unimng.Time_Block'),
        ),
    ]
